### ISSUE TITLE
Research and create basic pattern for timed jobs

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/dotacareer#1]
Should result in an example code that show us how we will do this.

Expected: 
- A cron job that ticks energy income on all players. 
- Also required energy on player model.
- Also make config for default start energy, and tick energy, and tick timer.

**Comment by bjorntore** [comment]
Unable to config the tick timer in .py file. Is it not OK to have that value in the cron.yaml file? That's where the job is set up anyways. Rest is done.

**Comment by Andrioden** [comment]
I agree.
