### ISSUE TITLE
Fix indentation in the html

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/dotacareer#13]
- sometimes class is on its own row
- sometimes the button teksts are on their own row. Keep each the element as one-rowed as possible.

**Comment by bjorntore** [comment]
Done. Also tweaked PyCharm to not do the stuff you mention above.

![andre](https://cloud.githubusercontent.com/assets/3596256/9660347/8bc9e388-5255-11e5-993a-a2a677bec988.PNG)
