### ISSUE TITLE
Register player - Choose personality traits

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/dotacareer#19]
Personality
- "Flamer": This player has a tendency to flame their opponents (- concentration on enemies) but this also increases his chance of flaming his own teammates (-concentration on friends). Is also resistant to flame and troll himself.
- "Arrogant": Always considers him the center of the team. Is confident (+ confidence) and has quick decision time (+something). Plays best as carry and mid (+ carry, +mid) but hates the other roles (- support, -ganker, -off lane).
- "The nice guy": The guy that is the first to say "I can support you bot" when you play together. (+MUCH support). Inceases team morale (+team moral). Weak to flaming (-flame resistance).

Tech notes:
- model stats_[statname] on player model is increased when class is chosen
- config of the personalities with description texts and values.

**Comment by bjorntore** [comment]
Base stats:
- stat_mid
- stat_offlane
- stat_support
- stat_carry
- stat_farm
- stat_gank
- stat_push
- stat_concentration
- stat_confidence
- stat_morale
- stat_troll
- stat_resistance_troll
