### ISSUE TITLE
Show all player stats under player profile

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/dotacareer#44]
- Do this dynamically by getting all stats_ values on player object.
- Also show it dynamically in GUI.

**Comment by Andrioden** [comment]
def get_stats_data(self):
        data = {}
        for variable_name in self.**dict**['_values'].keys(): # __dict__['_values'] contains all class object variables
            if 'stat_' in variable_name:
                variable_name_minus_stat_ = variable_name[5:]
                data[variable_name_minus_stat_] = round(getattr(self, variable_name), 1)
        return data

**Comment by bjorntore** [comment]
Lacking some responsive design, but better than at code review.

**Comment by bjorntore** [comment]
Commit:
https://github.com/Andrioden/dotacareer/commit/3ca54437712742638f67e866a1e83ee9e952ddf0
